# Generated by Django 4.0.4 on 2022-06-01 20:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('idProducto', models.AutoField(primary_key=True, serialize=False, verbose_name='Codigo de Producto')),
                ('nombreProducto', models.CharField(blank=True, max_length=30, null=True, verbose_name='Nombre del Producto')),
                ('descripcion', models.CharField(blank=True, max_length=100, null=True, verbose_name='Descripcion del Producto')),
                ('foto', models.ImageField(null=True, upload_to='', verbose_name='Foto del Producto')),
                ('precio', models.IntegerField(blank=True, null=True, verbose_name='Precio del Producto')),
                ('categoria', models.CharField(blank=True, max_length=20, null=True, verbose_name='Categoria del Producto')),
            ],
        ),
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('idRol', models.AutoField(primary_key=True, serialize=False, verbose_name='Codigo de Rol')),
                ('nombreRol', models.CharField(blank=True, max_length=30, null=True, verbose_name='Nombre del Rol')),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('idUsuario', models.AutoField(primary_key=True, serialize=False, verbose_name='Codigo de Usuario')),
                ('nombreUsuario', models.CharField(blank=True, max_length=30, null=True, verbose_name='Nombre del Usuario')),
                ('correoUsuario', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Correo del Usuario')),
                ('claveUsuario', models.CharField(blank=True, max_length=20, null=True, verbose_name='Clave del Usuario')),
                ('rol', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='AplicacionDjango.rol')),
            ],
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('idPedido', models.IntegerField(primary_key=True, serialize=False)),
                ('fecha', models.DateField(blank=True, null=True, verbose_name='Fecha de Pedido')),
                ('total', models.IntegerField(blank=True, null=True, verbose_name='Total a pagar')),
                ('cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='AplicacionDjango.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Boleta',
            fields=[
                ('id_boleta', models.AutoField(primary_key=True, serialize=False, verbose_name='Numero de registro')),
                ('cantidad', models.IntegerField(blank=True, null=True, verbose_name='Cantidad de producto')),
                ('subtotal', models.IntegerField(blank=True, null=True, verbose_name='Subtotal a pagar')),
                ('pedido', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='AplicacionDjango.pedido')),
                ('producto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='AplicacionDjango.producto')),
            ],
        ),
    ]
